### ISSUE TITLE
Thnx for a great work, but we need more examples. :)

### ISSUE THREAD

**Issue by bushemi** [brianzinn/create-react-app-babylonjs#1]
How to load your own .babylon model?  Or write a documentation about your classes. What is "code 0" ? 
"error: Unable to import meshes from"  ...   " Failed to load scene. Error status: 0  - Unable to load"
need to be described all properties of classes.

**Comment by brianzinn** [comment]
Can you make a fork of this repo with that issue?  As long as you have imported the loaders NPM with side-effects then you should be able to import .babylon models.
