### ISSUE TITLE
Invariant Violation: View config not found for name canvas. Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by DonavanMartin** [brianzinn/create-react-app-babylonjs#2]
<img width="351" alt="Capture d’écran, le 2020-01-12 à 14 52 07" src="https://user-images.githubusercontent.com/7544240/72224688-1e932300-354b-11ea-88a5-89cd8592376b.png">

**Comment by DonavanMartin** [comment]
This is not a React-native project... Dah!

**Comment by brianzinn** [comment]
@DonavanMartin  I had aspirations to setup this to work with React expo (expo.io), if you wanted to work together we could get that going...
