### ISSUE TITLE
Not able to start the app

### ISSUE THREAD

**Issue by TheCrowd** [brianzinn/create-react-app-babylonjs#5]
![image](https://user-images.githubusercontent.com/18615535/131456709-0406be3d-4cb5-43b8-8590-7094de4c37de.png)
I ran yarn install and yarn start, the above message came up.
I says failed to complie.
How do I resolve this?

**Comment by brianzinn** [comment]
I’ll fix that. I removed HostWithEvents and there’s since that example hooks added that make that easier. I will update today. Thank you for reporting

**Comment by brianzinn** [comment]
hi @TheCrowd - hope that commit solves it for you.  Please re-open if that doesn't fix it.
